
package com.mycompany.recuerdos;


/**
 *
 * @author Otro
 */
public class recuerdo extends javax.swing.JFrame {

    /**
     * Creates new form recuerdo
     */
    public recuerdo() {
        initComponents();
         combo.addItem("Opciones");
         combo.addItem("Declara Un ArrayList");
         combo.addItem("Array Con Un Sout");
         combo.addItem("Valor Dentro DeL Array");
        combo.addItem("for y dividir");
        combo.addItem("Tipos De Variable");
        combo.addItem("Get Datos De Usuario");
        sql.addItem("Opciones");
        sql.addItem("Conecion");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sql = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("        Tus Codigo Mostrado Por Mangel");

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        combo.setBackground(new java.awt.Color(153, 153, 255));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jLabel3.setText("ArrayList");

        jLabel4.setText("Base De Datos");

        sql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        String lista=(String)combo.getSelectedItem();
        if(lista.equals("Opciones")){
         eliminar(); 
        }
        if(lista.equals("Declara Un ArrayList")){
          jTextArea1.setText("\"  //Asi Se Declara Un ArrayList// \n" +
"                \n" +
"  \"ArrayList<nombredelalista> nuevonombre = new ArrayList<>(); \"\n" +
"                \n" +
                  "                \n" +
"ArrayList<String> nombreArrayList = new ArrayList<String>(); \n" +
"       \n" +
                  "                \n" +
"import java.util.ArrayList; // import the ArrayList class\n" +
" \n" +
                  "                \n" +
" ArrayList<String> cars = new ArrayList<String>(); // Create an ArrayList object \n" +
"                ;");      
    }//GEN-LAST:event_comboActionPerformed
if(lista.equals("Valor Dentro DeL Array")){
        jTextArea1.setText("\n"
                + "import java.util.ArrayList;\n" +
"\n" +
"public class Main {\n" +
"  public static void main(String[] args) {\n" +
"    ArrayList<String> cars = new ArrayList<String>();\n" +
"    cars.add(\"Volvo\");\n" +
"    cars.add(\"BMW\");\n" +
"    cars.add(\"Ford\");\n" +
"    cars.add(\"Mazda\");\n" +
"    System.out.println(cars);\n" +
"  }\n" +
"}");
    } 
    if(lista.equals("for y dividir")){
        jTextArea1.setText("  int migue=0;\n" +
"        for (int i = 1; i <=50; i++) {\n" +
"            if(i%2==0){\n" +
"                migue++;\n" +
"                System.out.println(migue);\n" +
"            }\n" +
"            \n" +
"        }\n" +
"     \n" +
"        for (int i = 1; i <= 50; i++) {\n" +
"            System.out.println(i);\n" +
"            \n" +
"        } ");
        
        
    }
    if(lista.equals("Get Datos De Usuario")){
        jTextArea1.setText(" if(e.getSource()==this.vista.ingresar1){\n" +
"            String id = this.vista.id.getText();\n" +
"            String nombr = this.vista.nombre.getText();\n" +
"            String apell = this.vista.apellido.getText();\n" +
"            this.eliminar();\n" +
"            liga.add(new lista(id, nombr, apell));\n" +
"            llenar(this.vista.tabla , liga);\n" +
"            JOptionPane.showMessageDialog(null, \"Dato Guardado\");\n" +
"        }");
    }
    if(lista.equals("Tipos De Variable")){
        jTextArea1.setText("int myNum = 5;\n" +
"float myFloatNum = 5.99f;\n" +
"char myLetter = 'D';\n" +
"boolean myBool = true;\n" +
"String myText = \"Hello\";");
    }
    }
    private void sqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqlActionPerformed
        // TODO add your handling code here:
        String base=(String)sql.getSelectedItem();
        if(base.equals("Opciones")){
         eliminar(); 
        }if (base.equals("Conecion")){
            jTextArea1.setText("\n" +
"import java.sql.Connection;\n" +
                    "\n" +
"import java.sql.DriverManager;\n" +
                    "\n" +
"import java.sql.SQLException;\n" +
                    "\n" +
"import java.util.logging.Level;\n" +
                    "\n" +
"import java.util.logging.Logger;\n" +
 "\n" +
                    
"abstract public class conecion {\n" +
 "\n" +
"public static final String URL =jdbc:mysql://localhost:3306/proyecto\n" +
                     "\n" +
"public static final String USER = root ;\n" +
                     "\n" +
"public static final String CLAVE = '  ' ;\n" +
                     "\n" +
"" +
" public Connection getConexion() {\n" +
                     "\n" +
"  Connection bn = null;\n" +
"" +
" try {\n" +
"   Class.forName(\\\"com.mysql.cj.jdbc.Driver\\\");\n" +
                     "\n" +
"   bn = DriverManager.getConnection(URL, USER, CLAVE);\n" +
                     "\n" +
"   } catch (SQLException e) {\n" +
                     "\n" +
"   System.out.println(\\\"ERROR\\\" + e.getMessage());\n" +
                     "\n" +
"   } catch (ClassNotFoundException x) {\n" +
                     "\n" +
"   Logger.getLogger(conecion.class.getName()).log(Level.SEVERE, null, x);\n" +
                     "\n" +
"" +
"}return bn ;"+

                   "" );
        }
        
        
    }//GEN-LAST:event_sqlActionPerformed
    

    
    
    
    public void eliminar(){
        jTextArea1.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recuerdo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recuerdo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recuerdo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recuerdo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recuerdo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> sql;
    // End of variables declaration//GEN-END:variables
}
